theme: jekyll-theme-minimal
title: ArkScript lang
logo: /assets/images/ArkTransparent-by-mazz.png
description: A small, fast, functional and scripting language for video games
show_downloads: true
google_analytics: